name: TIO-CS-SCANNER

on: push

jobs:
  CS-SCANNER:
    name: Tenable.io Container Security Scanner Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Container Security Scanner
        run:  |
          docker login tenableio-docker-consec-local.jfrog.io -u pubread -p BXaXRD9n3uEWKkGgt56eHVD5h
          
